### ISSUE TITLE
i'm Still waiting for the Coming soon

### ISSUE THREAD

**Issue by VoipSip** [ofasgard/sipfurious#2]
'map' over TCP
'war' over TCP
'crack' over TCP
'map' over TLS
'war' over TLS
'crack' over TLS

**Comment by ofasgard** [comment]
I'm not actively working on this tool at the moment, but it may be something I return to in the near future.

**Comment by ofasgard** [comment]
TCP support implemented, TLS will have to wait until the basic functionality has been tested more thoroughly.

**Comment by VoipSip** [comment]
thank you very much for your wonderful effort
