### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by VoipSip** [ofasgard/sipfurious#3]
Hello sir thank you for the wonderful script  but some problem i found like how to scan range ip list and how to using war and crack also at ip range from file list

**Comment by VoipSip** [comment]
bin/sipfurious map udp 192.168.1.1/13 5060 
cidr or range  192.168.1.0-192.1.1.1
also if i want to put the ranges or cidr on file list and he is pull from the file list and start scanning and save the result on file outside

**Comment by VoipSip** [comment]
some other problem 

Unrecognised status code during initial check: SIP/2.0 100 Trying

No results found.

**Comment by VoipSip** [comment]
also when i start testing crack check by your self 

bin/sipfurious --wordlist users.txt --user 100 crack udp 193.226.38.22
Trying 193.226.38.22:5060...
Unrecognised status code during initial check: SIP/2.0 100 Trying

No results found

also the password of this ip is 100 but he can't found

**Comment by ofasgard** [comment]
Hard to diagnose these issues remotely, but I recommend trying to increase the throttle and/or timeout if you're getting "unrecognised status code" errors. 

I'm not sure what you mean about scanning ranges of IPs, but you should be able to do something like:

$ sipfurious map udp 127.0.0.0/16

To scan a CIDR range. I'll look into the "100 trying" issue, I think that might be a status code I need to tell the program to ignore.

**Comment by ofasgard** [comment]
I've updated it to ignore "100 trying" and keep listening for a response in commit ff71d28, hopefully this fixes your issue.
